export const props = [
    ['action', '请求 URL', 'string', '—', '—'],
    ['headers', '设置上传的请求头部', 'Headers | Record<string, any>', '—', '—'],
    ['method', '设置上传请求方法', 'string', '—', '`post`'],
    ['multiple', '是否支持多选文件', 'boolean', '—', 'false'],
    ['data', '上传时附带的额外参数', 'Record<string, any>', '—', '—'],
    ['name', '上传的文件字段名', 'string', '—', '`file`'],
    ['withCredentials', '支持发送 cookie 凭证信息', 'boolean', '—', 'false'],
    ['showFileList', '是否显示已上传文件列表', 'boolean', '—', 'true'],
    ['drag', '是否启用拖拽上传', 'boolean', '—', 'false'],
    ['accept', '接受上传的文件类型（thumbnail-mode 模式下此参数无效）', 'string', '—', '—'],
    ['onPreview', '点击文件列表中已上传的文件时的钩子', '(uploadFile: UploadFile) => void', '—', '—'],
    ['onRemove', '文件列表移除文件时的钩子', '(uploadFile: UploadFile, uploadFiles: UploadFiles) => void', '—', '—'],
    ['onSuccess', '文件上传成功时的钩子', '(response: any, uploadFile: UploadFile, uploadFiles: UploadFiles) => void', '—', '—'],
    ['onError', '文件上传失败时的钩子', '(error: Error, uploadFile: UploadFile, uploadFiles: UploadFiles) => void', '—', '—'],
    ['onProgress', '文件上传时的钩子', '(evt: UploadProgressEvent, uploadFile: UploadFile, uploadFiles: UploadFiles) => void', '—', '—'],
    ['onChange', '文件状态改变时的钩子，添加文件、上传成功和上传失败时都会被调用', '(uploadFile: UploadFile, uploadFiles: UploadFiles) => void', '—', '—'],
    ['onExceed', '当超出限制时，执行的钩子函数', '(files: File[], uploadFiles: UploadFiles) => void', '—', '—'],
    ['beforeUpload', '上传文件之前的钩子，参数为上传的文件， 若返回false或者返回 Promise 且被 reject，则停止上传。', '(rawFile: UploadRawFile) => Awaitable<void | undefined | null | boolean | File | Blob>', '—', '—'],
    ['beforeRemove', '删除文件之前的钩子，参数为上传的文件和文件列表， 若返回 false 或者返回 Promise 且被 reject，则停止删除。', '(uploadFile: UploadFile, uploadFiles: UploadFiles) => Awaitable<boolean>', '—', '—'],
    ['fileList', '默认上传文件', 'UploadUserFile[]', '—', '[]'],
    ['listType', '文件列表的类型', '`text` | `picture` | `pictureCard`', '—', '`text`'],
    ['autoUpload', '是否自动上传文件', 'boolean', '—', 'true'],
    ['httpRequest', '覆盖默认的 Xhr 行为，允许自行实现上传文件的请求', '(options: UploadRequestOptions) => XMLHttpRequest | Promise<unknown>', '—', '—'],
    ['disabled', '是否禁用上传', 'boolean', '—', 'false'],
    ['limit', '允许上传文件的最大数量', 'number', '—', '—'],
    ['formatter', '缩略图模板的内容', '(file: UploadFile) => React.ReactElement', '—', '—'],
    ['triggerSlot', '触发文件选择框的内容', 'React.ReactElement', '—', '—'],
    ['tip', '提示说明文字', 'React.ReactElement', '—', '—'],
];

export const ref = [
    ['abort', '取消上传请求', '(file: UploadFile) => void'],
    ['submit', '手动上传文件列表', '() => void'],
    ['clearFiles', '清空已上传的文件列表（该方法不支持在 beforeUpload 中调用）', '(status?: Array<"ready" | "uploading" | "success" | "fail">) => void'],
    ['handleStart', '手动选择文件', '(rawFile: UploadRawFile) => void'],
    ['handleRemove', '手动移除文件。 file 和rawFile 已被合并。 rawFile 将在 v2.2.0 中移除', '(file: UploadFile | UploadRawFile, rawFile?: UploadRawFile) => void'],
];
